version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    user: '1000:1000'
    volumes:
      - './Project/:/app'

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - './Project/:/app'
      - './docker/nginx:/etc/nginx/conf.d'
